stages:
  - build
  - deploy

variables:
  DOCKER_REGISTRY: "docker.io"
  IMAGE_NAME: "kursatartar/nodejs-express-mysql"
  HELM_RELEASE_NAME: "chart-case"
  NAMESPACE: "default"
  HELM_CHART_DIR: "./chart-case"
  VALUES_FILE: "./chart-case/values.yml"
  DOCKER_DRIVER: "overlay2" # Docker için sürücü belirt

# Docker imajını oluşturma ve push işlemi
build:
  stage: build
  image: docker:latest  # Docker'ın en son sürümünü kullanalım
  services:
    - docker:19.03.12-dind  # Docker-in-Docker servisini ekliyoruz
  script:
    - echo "Building Docker image..."
    - |
      # Branch adı göre uygun IMAGE_TAG değerini belirleyelim
      case "$CI_COMMIT_REF_NAME" in
        "main")
          export IMAGE_TAG="latest"
          ;;
        "staging")
          export IMAGE_TAG="staging"
          ;;
        *)
          export IMAGE_TAG="dev"
          ;;
      esac
    - echo "Tagging Docker image as $IMAGE_TAG"
    - docker build -t $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
    - docker push $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
  only:
    - main
    - staging

# Deploy işlemi - production (main branch)
deploy_main:
  stage: deploy
  image: node:16  # Node.js Docker imajı
  script:
    - echo "Deploying to production (main branch)..."
    - helm upgrade --install $HELM_RELEASE_NAME $HELM_CHART_DIR -f $VALUES_FILE --namespace $NAMESPACE
  only:
    - main

# Deploy işlemi - staging branch
deploy_staging:
  stage: deploy
  image: node:16  # Node.js Docker imajı
  script:
    - echo "Deploying to staging..."
    - helm upgrade --install $HELM_RELEASE_NAME $HELM_CHART_DIR -f $VALUES_FILE --namespace $NAMESPACE
  only:
    - staging
