apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-express-mysql  # Uygulama adı
  namespace: argocd           # ArgoCD'nin kurulu olduğu namespace
spec:
  project: default            # ArgoCD'deki proje adı (varsayılan: default)
  source:
    repoURL: 'https://github.com/kursatartar/codeway-casegit'  # Proje repo URL'si
    targetRevision: main       # Git branch (örnek: main)
    path: chart-case           # Helm chart'ın bulunduğu dizin
  destination:
    server: 'https://kubernetes.default.svc'  # Kubernetes API server adresi (default küme içi erişim)
    namespace: nodejs-app      # Uygulamanın yükleneceği namespace
  syncPolicy:
    automated:
      prune: true              # Eski kaynakları temizler
      selfHeal: true           # Kubernetes ile durum uyumsuzsa düzeltir

