apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-express-mysql  # app name
  namespace: argocd           # argocd namespace
spec:
  project: default            # default value for argocd
  source:
    repoURL: 'https://github.com/kursatartar/codeway-case.git'  
    targetRevision: main       # git branch
    path: chart-case           # directory
  destination:
    server: 'https://kubernetes.default.svc'  # kubernetes api
    namespace: nodejs-app      
  syncPolicy:
    automated:
      prune: true              
      selfHeal: true       

