version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:8080"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_NAME=testdb
    secrets:
      - db_password
    depends_on:
      - db

  db:
    image: mysql:8.0
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_password

volumes:
  db_data:


secrets:
  db_password:
    file: ./db_password.txt
