apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-express-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kursatartar/codeway-case.git'
    targetRevision: staging
    path: chart-case
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true